#!/bin/bash
#
# check Hetzner backup free space
#
# based on http://exchange.nagios.org/directory/Plugins/Operating-Systems/Linux/check_users-2Esh/details
#
##########################################################

help() {
    echo "Usage: $0 -w warn -c crit"
    echo
    echo "  'warn' and 'crit' are integers between 0 and 100 (percent)"
    echo
    echo "  check free disk space on Hetzner backup"
    echo
    echo "  Example: $0 -w 20 -c 5"
    exit 3
}

status_and_exit() {
  echo "$1: Hetzner backup is ${used}% used | used=${used}%;;;;"
  exit $2
}

# parse args
for i in first_arg second_arg; do

  if   [ "$2" == "" ]; then
    help
  fi

  if   [ "$1" == "-w" ]; then
    warn=$2
  elif [ "$1" == "-c" ]; then
    crit=$2
  else
    help
  fi

  shift
  shift
done

# get free space
df=`sudo /usr/local/bin/backup-df -h 2>/dev/null | tail -n 1`
used=`echo "$df" | awk '{ print $5 }' | tr -d '%'`
free=$(( 100 - $used ))

# compare with warning/critical levels and emit status
if [ $free -gt $warn ]; then
  status_and_exit OK 0
elif [ $free -le $warn -a $free -gt $crit ]; then
  status_and_exit Warning 1
elif [ $free -le $crit ]; then
  status_and_exit Critical 1
else
  echo "Unknown error"
  exit 3
fi

